<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.StatusProto" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/MPCore.Application/MPCore.Application.csproj" />
    <ProjectReference Include="../../src/MPCore.Transport.Grpc/MPCore.Transport.Grpc.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="Protos/failure_probe.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
