<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>MPCore.Caching.Memory</PackageId>
    <Description>In-memory implementation of the MP Core cache port.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../MPCore.Caching.Abstractions/MPCore.Caching.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
</Project>
