<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/MPCore.Observability/MPCore.Observability.csproj" />
    <ProjectReference Include="../../src/MPCore.Observability.Prometheus/MPCore.Observability.Prometheus.csproj" />
  </ItemGroup>
</Project>
