<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/MPCore.Audit.EntityFrameworkCore.PostgreSql/MPCore.Audit.EntityFrameworkCore.PostgreSql.csproj" />
    <ProjectReference Include="../../src/MPCore.Persistence.EntityFrameworkCore.PostgreSql/MPCore.Persistence.EntityFrameworkCore.PostgreSql.csproj" />
  </ItemGroup>
</Project>
